# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PassCli < Formula
  desc "Secure, cross-platform CLI password and API key manager for developers"
  homepage "https://github.com/ari1110/pass-cli"
  version "0.10.0"
  license "MIT"

  on_macos do
    url "https://github.com/ari1110/pass-cli/releases/download/v0.10.0/pass-cli_0.10.0_darwin_all.tar.gz"
    sha256 "ec89c19bc8caf8c1a393db706444e0428e364c2da108fea4cc5cf791116b64d2"

    def install
      bin.install "pass-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ari1110/pass-cli/releases/download/v0.10.0/pass-cli_0.10.0_linux_x86_64.tar.gz"
      sha256 "4ccd78183f468afb46150530ae22869523c0ba813a42e4feccc7976236894fa9"
      def install
        bin.install "pass-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ari1110/pass-cli/releases/download/v0.10.0/pass-cli_0.10.0_linux_arm64.tar.gz"
      sha256 "8d7b7631731fd34dbb089c882b8c5d6a1c91f16e2bfdfafa60772db95f32bec8"
      def install
        bin.install "pass-cli"
      end
    end
  end

  def caveats
    <<~EOS
      Pass-CLI: Secure password manager with TUI and CLI interfaces

      First-time users: Run `pass-cli` (no arguments) for guided setup.

      Quick start:
        pass-cli          - Launch interactive TUI
        pass-cli init     - Initialize vault manually
        pass-cli doctor   - Run health checks

      Features:
        • Interactive TUI for visual management
        • Keychain integration: pass-cli keychain enable
        • Usage tracking and audit logging

      Vault location: ~/.pass-cli/vault.enc
      Complete guide: https://github.com/ari1110/pass-cli/blob/main/docs/GETTING_STARTED.md
    EOS
  end

  test do
    system "#{bin}/pass-cli", "version"
  end
end
